# Generated by Django 4.1.13 on 2024-02-28 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=50, verbose_name='Отчество')),
                ('experience', models.IntegerField(default=1, verbose_name='Стаж')),
                ('description', models.TextField(default='Описание', max_length=2000, verbose_name='Описание')),
                ('photo', models.ImageField(default='recipient_photo/recipient.jpg', null=True, upload_to='recipient_photo', verbose_name='Фотография')),
            ],
            options={
                'verbose_name': 'Обозреваемый',
                'verbose_name_plural': 'Обозреваемые',
                'ordering': ['-second_name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Специальность')),
            ],
            options={
                'verbose_name': 'Специальность',
                'verbose_name_plural': 'Специальности',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_review', models.CharField(max_length=2000, verbose_name='Исходный отзыв')),
                ('modified_review', models.CharField(max_length=2000, verbose_name='Измененный отзыв')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время изменения')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('rate', models.IntegerField(default=5, verbose_name='Оценка')),
                ('user_ip', models.GenericIPAddressField(verbose_name='Айпи адрес рецензента')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Рецензент', to=settings.AUTH_USER_MODEL, verbose_name='')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'Отзывы',
                'ordering': ['time_create'],
            },
        ),
        migrations.AddIndex(
            model_name='recipient',
            index=models.Index(fields=['-second_name'], name='recipient_r_second__c3f8e8_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['time_create'], name='recipient_r_time_cr_ac1065_idx'),
        ),
    ]
