# Generated by Django 4.1.13 on 2024-02-28 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='specialities',
            field=models.ManyToManyField(related_name='recipients', to='recipient.specialty'),
        ),
        migrations.AddField(
            model_name='review',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='recipient.recipient', verbose_name='Обозреваемый'),
        ),
    ]
