# Generated by Django 4.1.13 on 2024-03-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_recipient_specialities_review_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимный отзыв'),
        ),
        migrations.AlterField(
            model_name='review',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
